[project]
name = "reppi"
version = "1.0.0"
readme = "README.md"
description = "A modular Python toolkit for sparse representation-based learning/classification algorithms"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.4",
    "scipy>=1.17.1",
    "torch>=2.14.0",
    "tqdm>=4.68.4",
]

[build-system]
requires = [
    "setuptools>=61.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "pdoc>=16.0.0",
]
